#!/usr/bin/env bash
# display pid with process name containing bash
for pid in /proc/*/; do
    pid=${pid%/}

    if [ -e "$pid/cmdline" ] && grep -q "/bash" "$pid/cmdline"; then
        process_name=$(tr '\0' ' ' < "$pid/cmdline")
        echo "${pid##*/} $process_name"
    fi
done
