#!/usr/bin/env bash
# print Best school 10 times and hi in new line
i=0
while [ $i -le 10 ]; do
  if [ $i -eq 9 ]; then
    echo -e "Best School\nHi"
  else
    echo "Best School"
  fi

  ((i++))
done

